namespace FluffyByte.OPUL.Core.FluffyIO.FluffyConsole;

/// <summary>
/// Specifies the level of logging detail for the Fluffy logging system.
/// </summary>
/// <remarks>The <see cref="FluffyLogLevel"/> enumeration defines the severity or category of log messages that
/// can be generated by the system. It allows filtering of log output based on the specified level, enabling developers
/// to focus on messages of interest.</remarks>
public enum FluffyLogLevel
{
    Debug,
    Info,
    Warning,
    Error,
    Critical,
    Network,
    Performance
}
